[package]
name = "mango"
version = "0.1.0"
authors = ["Tamiyo <matthewgmcmillian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
string-interner = "0.7.1"
structopt = { version = "0.3" }