%{ 
# Ignore This
NTS_CTRL -> NTS_CTRL_IF NTS_CTRL_ELSEIF NTS_CTRL_ELSE

NTS_CTRL_IF -> TS_IF TS_LPAREN NTS_COND TS_RPAREN TS_LCB NTS_STMTS TS_RCB
NTS_CTRL_ELSEIF -> TS_ELSEIF TS_SPACE NTS_COND TS_SPACE TS_LCB NTS_STMTS TS_RCB
NTS_CTRL_ELSEIF -> ''

NTS_CTRL_ELSE -> TS_ELSE TS_SPACE TS_LCB NTS_STMTS TS_RCB
NTS_CTRL_ELSE -> ''

NTS_COND -> TS_VARIABLE NTS_COND_OPERATOR TS_VARIABLE
NTS_COND -> NTS_COND_S_OPERATOR TS_VARIABLE
%}